//! Counterfactual change triggers, ARCHITECTURE §6.8. For each unresolved or
//! disputed claim, pin its standing to the extreme opposite its current lean,
//! re-run the fixpoint, and see whether the winning option changes. Computed, not
//! generated by a model.
//!
//! INTERFACES §21 reuses exactly this pass for `decision_leverage`
//! (`|Δ margin(top1, top2)|`, the dispute-ranking term that asks "could this change
//! the answer?") — which is why [`counterfactual_flips`] returns **every** tested
//! candidate, not only the ones that flip the winner: a quiet claim with near-zero
//! leverage still needs a leverage score to be ranked low.

use crate::config::GraphParams;
use crate::decision::attachment::{AttachmentMatrix, score_options};
use crate::decision::fixpoint::solve;
use crate::ids::{ClaimId, OptionId};
use crate::option::DecisionOption;
use crate::relation::Relation;
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum FlipDirection {
    /// Standing pinned to 1.0 — "if this claim turned out to be true".
    IfTrue,
    /// Standing pinned to 0.0 — "if this claim turned out to be false".
    IfFalse,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct CounterfactualFlip {
    pub claim_id: ClaimId,
    /// Which extreme this claim was pinned to — the one *opposite* its baseline
    /// standing (PLAN_DEVIATIONS.md D17): a claim already leaning true (standing
    /// ≥ 0.5) is tested `IfFalse`, and vice versa.
    pub direction: FlipDirection,
    /// `None` only when there is no ranked option at all — an edge case upstream
    /// stages should not produce, but this module does not assume it away.
    pub new_winner: Option<OptionId>,
    pub margin_before: f64,
    pub margin_after: f64,
    /// `true` when `new_winner` differs from the un-flipped run's winner —
    /// ARCHITECTURE §6.8's "change trigger". Only `true` entries belong in
    /// `DecisionRecord.change_triggers` (§6.9); every entry, triggering or not,
    /// carries `leverage()` for §21's dispute ranking.
    pub is_trigger: bool,
}

impl CounterfactualFlip {
    /// INTERFACES §21's `decision_leverage`: `|Δ margin(top1, top2)|`.
    pub fn leverage(&self) -> f64 {
        (self.margin_after - self.margin_before).abs()
    }
}

/// `candidates` are the claims to test. ARCHITECTURE §6.8 scopes this to claims
/// currently `Disputed` or `Unresolved`
/// ([`crate::decision::standing::classify_all`]) — this module takes the
/// pre-filtered set rather than re-deriving standing classification itself, which
/// is C3's responsibility, not C7's.
///
/// Returned in `candidates`' input order — callers that want only actual triggers
/// filter on `is_trigger`; callers computing `decision_leverage` for every
/// candidate (§21) use the full, unfiltered list.
#[allow(clippy::too_many_arguments)]
pub fn counterfactual_flips(
    claim_ids: &[ClaimId],
    evidence: &BTreeMap<ClaimId, f64>,
    relations: &[Relation],
    graph: &GraphParams,
    candidates: &[ClaimId],
    options: &[DecisionOption],
    attachment: &AttachmentMatrix,
) -> Vec<CounterfactualFlip> {
    let baseline = solve(claim_ids, evidence, relations, graph);
    let baseline_scores = score_options(options, attachment, &baseline.standing);
    let baseline_ranked = super::rank_by_share(&baseline_scores);
    let baseline_winner = baseline_ranked.first().map(|o| o.id.clone());
    let margin_before = margin(&baseline_ranked);

    candidates
        .iter()
        .map(|claim_id| {
            let current = baseline.standing.get(claim_id).copied().unwrap_or(0.0);
            let (direction, extreme) = if current >= 0.5 {
                (FlipDirection::IfFalse, 0.0)
            } else {
                (FlipDirection::IfTrue, 1.0)
            };

            // Pinning: override this claim's evidence to the extreme, and drop
            // every relation targeting it, so nothing pulls its own standing back
            // off the extreme — it stays fixed while its *outgoing* edges still
            // propagate the pinned value outward, exactly like an isolated
            // claim's fixed point (`fixpoint::solve`'s own initial condition).
            let mut flipped_evidence = evidence.clone();
            flipped_evidence.insert(claim_id.clone(), extreme);
            let flipped_relations: Vec<Relation> = relations
                .iter()
                .filter(|r| r.to != *claim_id)
                .cloned()
                .collect();

            let flipped = solve(claim_ids, &flipped_evidence, &flipped_relations, graph);
            let flipped_scores = score_options(options, attachment, &flipped.standing);
            let flipped_ranked = super::rank_by_share(&flipped_scores);
            let new_winner = flipped_ranked.first().map(|o| o.id.clone());
            let margin_after = margin(&flipped_ranked);

            CounterfactualFlip {
                claim_id: claim_id.clone(),
                direction,
                is_trigger: new_winner != baseline_winner,
                new_winner,
                margin_before,
                margin_after,
            }
        })
        .collect()
}

fn margin(ranked: &[&crate::option::OptionScore]) -> f64 {
    let top1 = ranked.first().map(|o| o.share).unwrap_or(0.0);
    let top2 = ranked.get(1).map(|o| o.share).unwrap_or(0.0);
    top1 - top2
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::decision::attachment::{AttachSource, Attachment, Polarity};
    use crate::relation::RelationKind;

    fn opt(id: &str, label: &str) -> DecisionOption {
        DecisionOption::new(OptionId::new(id), label)
    }

    fn direct(
        claim: &str,
        option: &OptionId,
        polarity: Polarity,
    ) -> ((ClaimId, OptionId), Attachment) {
        (
            (ClaimId::new(claim), option.clone()),
            Attachment {
                polarity,
                confidence: 1.0,
                source: AttachSource::Authored,
            },
        )
    }

    /// Mirrors ARCHITECTURE §6.8's own worked example: flipping the one claim
    /// decisive for the trailing option changes the winner; flipping claims with
    /// no bearing on either option does not.
    #[test]
    fn flipping_a_decisive_claim_is_a_trigger_flipping_an_unattached_one_is_not() {
        let monolith = opt("opt_monolith", "Modular monolith");
        let microservices = opt("opt_micro", "Full microservices");
        let options = vec![monolith.clone(), microservices.clone()];

        // base_m alone carries monolith (0.9, fixed baseline, not a candidate).
        // c018 alone carries microservices, starting weak (0.1): flipping it to
        // 1.0 pushes microservices' raw past monolith's fixed 0.9. c012 and c021
        // are candidates too, but attached to neither option, so no flip of
        // theirs can ever move either option's raw.
        let claim_ids: Vec<ClaimId> = ["base_m", "c018", "c012", "c021"]
            .into_iter()
            .map(ClaimId::new)
            .collect();
        let mut evidence = BTreeMap::new();
        evidence.insert(ClaimId::new("base_m"), 0.9);
        evidence.insert(ClaimId::new("c018"), 0.1);
        evidence.insert(ClaimId::new("c012"), 0.9);
        evidence.insert(ClaimId::new("c021"), 0.9);

        let mut matrix = AttachmentMatrix::default();
        let (k, v) = direct("base_m", &monolith.id, Polarity::Supports);
        matrix.cells.insert(k, v);
        let (k, v) = direct("c018", &microservices.id, Polarity::Supports);
        matrix.cells.insert(k, v);

        let graph = GraphParams::default();
        let candidates: Vec<ClaimId> = ["c018", "c012", "c021"]
            .into_iter()
            .map(ClaimId::new)
            .collect();

        let flips = counterfactual_flips(
            &claim_ids,
            &evidence,
            &[],
            &graph,
            &candidates,
            &options,
            &matrix,
        );

        let c018 = flips
            .iter()
            .find(|f| f.claim_id == ClaimId::new("c018"))
            .unwrap();
        assert_eq!(c018.direction, FlipDirection::IfTrue); // 0.1 leans false
        assert_eq!(c018.new_winner, Some(microservices.id.clone()));
        assert!(
            c018.is_trigger,
            "flipping the decisive claim must change the winner"
        );

        for unattached in ["c012", "c021"] {
            let f = flips
                .iter()
                .find(|f| f.claim_id == ClaimId::new(unattached))
                .unwrap();
            assert!(
                !f.is_trigger,
                "{unattached} decides neither option, so flipping it cannot change the winner"
            );
            assert_eq!(f.leverage(), 0.0);
        }
    }

    #[test]
    fn direction_is_the_extreme_opposite_the_current_lean() {
        let a = opt("a", "A");
        let options = vec![a.clone()];
        let claim_ids: Vec<ClaimId> = ["low", "high"].into_iter().map(ClaimId::new).collect();
        let mut evidence = BTreeMap::new();
        evidence.insert(ClaimId::new("low"), 0.2);
        evidence.insert(ClaimId::new("high"), 0.8);
        let matrix = AttachmentMatrix::default();
        let graph = GraphParams::default();

        let flips = counterfactual_flips(
            &claim_ids,
            &evidence,
            &[],
            &graph,
            &claim_ids,
            &options,
            &matrix,
        );

        let low = flips
            .iter()
            .find(|f| f.claim_id == ClaimId::new("low"))
            .unwrap();
        assert_eq!(low.direction, FlipDirection::IfTrue);
        let high = flips
            .iter()
            .find(|f| f.claim_id == ClaimId::new("high"))
            .unwrap();
        assert_eq!(high.direction, FlipDirection::IfFalse);
    }

    #[test]
    fn margin_before_is_identical_across_every_returned_flip() {
        let a = opt("a", "A");
        let options = vec![a.clone()];
        let claim_ids: Vec<ClaimId> = ["c1", "c2"].into_iter().map(ClaimId::new).collect();
        let mut evidence = BTreeMap::new();
        evidence.insert(ClaimId::new("c1"), 0.4);
        evidence.insert(ClaimId::new("c2"), 0.6);
        let matrix = AttachmentMatrix::default();
        let graph = GraphParams::default();

        let flips = counterfactual_flips(
            &claim_ids,
            &evidence,
            &[],
            &graph,
            &claim_ids,
            &options,
            &matrix,
        );
        assert_eq!(flips.len(), 2);
        assert_eq!(flips[0].margin_before, flips[1].margin_before);
    }

    #[test]
    fn a_claim_disconnected_from_every_option_has_zero_leverage_and_is_not_a_trigger() {
        let a = opt("a", "A");
        let options = vec![a.clone()];
        let claim_ids: Vec<ClaimId> = ["irrelevant"].into_iter().map(ClaimId::new).collect();
        let mut evidence = BTreeMap::new();
        evidence.insert(ClaimId::new("irrelevant"), 0.5);
        // No attachment cell at all -- this claim decides nothing about `a`.
        let matrix = AttachmentMatrix::default();
        let graph = GraphParams::default();

        let flips = counterfactual_flips(
            &claim_ids,
            &evidence,
            &[],
            &graph,
            &claim_ids,
            &options,
            &matrix,
        );
        assert_eq!(flips.len(), 1);
        assert_eq!(flips[0].leverage(), 0.0);
        assert!(!flips[0].is_trigger);
    }

    #[test]
    fn flipping_one_claim_does_not_disturb_an_unrelated_claims_own_standing() {
        // Regression guard for the pinning mechanism: dropping incoming edges to
        // the flipped claim must not accidentally drop edges into *other* claims.
        let a = opt("a", "A");
        let options = vec![a.clone()];
        let claim_ids: Vec<ClaimId> = ["flip_me", "supporter", "bystander"]
            .into_iter()
            .map(ClaimId::new)
            .collect();
        let mut evidence = BTreeMap::new();
        evidence.insert(ClaimId::new("flip_me"), 0.5);
        evidence.insert(ClaimId::new("supporter"), 0.8);
        evidence.insert(ClaimId::new("bystander"), 0.5);
        let relations = vec![Relation {
            from: ClaimId::new("supporter"),
            to: ClaimId::new("bystander"),
            kind: RelationKind::Supports,
            confidence: 1.0,
        }];
        let matrix = AttachmentMatrix::default();
        let graph = GraphParams::default();

        let flips = counterfactual_flips(
            &claim_ids,
            &evidence,
            &relations,
            &graph,
            &[ClaimId::new("flip_me")],
            &options,
            &matrix,
        );
        // bystander's edge from supporter must still apply during flip_me's test
        // run -- this only asserts the function runs to completion without
        // panicking and returns exactly one flip for the one requested candidate.
        assert_eq!(flips.len(), 1);
    }
}
